#!/bin/bash
set -eu

/opt/stack/venvs/cinder/bin/cinder-manage db sync

os-svc-enable -n cinder-api
os-svc-enable -n cinder-scheduler

service cinder-scheduler restart
service cinder-api restart

os-svc-enable -n cinder-volume
service cinder-volume restart
service tgtd restart








